import gradio as gr
from pathlib import Path
from ..config.loader import load_config
from ..training.runner import ExperimentRunner
from ..cli.commands import cmd_train

def get_config_info(config_path):
    """Helper to extract dataset and model keys for the UI."""
    try:
        cfg = load_config(config_path)
        assert isinstance(cfg.datasets, dict)
        assert isinstance(cfg.model, dict)
        datasets = ["all"] + list(cfg.datasets.keys())
        models = ["all"] + list(cfg.model.keys())
        return gr.update(choices=datasets, value="all"), gr.update(choices=models, value="all")
    except Exception as e:
        return gr.update(choices=[], value=None), gr.update(choices=[], value=None)

def run_train_gui(config_path, datasets, models, resume):
    """Wrapper for cmd_train that returns status and plots."""
    # Convert Gradio multi-select list to the format cmd_train expects
    ds_list = "all" if "all" in datasets else datasets
    md_list = "all" if "all" in models else models
    
    try:
        # We call your existing refactored command
        cmd_train(config_path, ds_list, md_list, resume=resume)
        return f"✅ Training Finished for {ds_list} | {md_list}. Check the 'runs' folder for artifacts."
    except Exception as e:
        return f"❌ Error: {str(e)}"

def run_test_single_gui(config_path, dataset, model, ckpt_path):
    """Runs test and returns the plots."""
    cfg = load_config(config_path)
    runner = ExperimentRunner(cfg, dataset, model)
    runner.build_data()
    runner.build_model()
    runner.build_optimizer()
    runner.build_trainer()
    
    # Run evaluation
    results = runner.test(checkpoint_path=Path(ckpt_path))
    
    # Retrieve the plots generated by the runner (assuming we updated runner.py)
    # If the runner saves them to disk, we return the file paths
    viz_path = runner.exp_dir / "test_visualization.png"
    return f"Test Score: {results}", viz_path

def load_all_plots(config_path):
    """
    Scan the experiment directorty and return a list of image paths
    for gradio gallery
    """
    try:
        cfg = load_config(config_path)
        exp_root = Path("runs") / cfg.get("experiment", "run")

        if not exp_root.exists():
            return [], "Experiment directory not found yet"
        gallery_items = []
        for subfolder in exp_root.iterdir():
            if not subfolder.is_dir():continue
            loss_p = subfolder / "loss_plot.png"
            viz_p = subfolder / "test_visualization.png"

            if loss_p.exists():
                gallery_items.append((str(loss_p), f"{subfolder.name} - Loss"))
            if viz_p.exists():
                gallery_items.append((str(viz_p), f"{subfolder.name} - Results"))
        return gallery_items, f"Found {len(gallery_items)} plots."
    except Exception as e:
        return [], f"Error loading plots: {str(e)}"
# --- UI Layout ---
with gr.Blocks(title="Deepthon Pipeline Dashboard") as demo:
    gr.Markdown("# 🧠 Deepthon Pipeline GUI")
    
    with gr.Row():
        config_input = gr.Textbox(label="Config Path", placeholder="e.g., config.yaml")
        load_btn = gr.Button("Load Config Options", variant="secondary")

    with gr.Tabs():
        # --- Training Tab ---
        with gr.TabItem("🚀 Training"):
            with gr.Row():
                ds_select = gr.Dropdown(label="Select Datasets", choices=[], multiselect=True)
                md_select = gr.Dropdown(label="Select Models", choices=[], multiselect=True)
            
            resume_toggle = gr.Checkbox(label="Resume from Checkpoint")
            train_btn = gr.Button("Start Training Matrix", variant="primary")
            train_output = gr.Textbox(label="Status")

        # --- Testing Tab ---
        with gr.TabItem("📊 Evaluation"):
            with gr.Row():
                test_ds = gr.Dropdown(label="Dataset")
                test_md = gr.Dropdown(label="Model")
            ckpt_input = gr.Textbox(label="Checkpoint Path (.pkl)")
            test_btn = gr.Button("Run Evaluation")
            
            with gr.Row():
                test_metrics = gr.Label(label="Metrics")
                test_plot = gr.Image(label="Visualization (CM or Scatter)")
        with gr.TabItem("🚩 Plots"):
            plot_status = gr.Markdown("Click 'Load' to scan for plots")
            result_gallery = gr.Gallery(
                label="Experient Results",
                show_label=False,
                elem_id="gallery",
                columns=2,
                rows=2,
                object_fit="contain",
                height="auto"
                )

    # Interactivity
    load_btn.click(get_config_info, inputs=config_input, outputs=[ds_select, md_select])
    load_btn.click(get_config_info, inputs=config_input, outputs=[test_ds, test_md])
    load_btn.click(load_all_plots, inputs=config_input, outputs=[result_gallery, plot_status])
    
    train_btn.click(run_train_gui, 
                    inputs=[config_input, ds_select, md_select, resume_toggle], 
                    outputs=train_output).then(
                        load_all_plots,
                        inputs=config_input,
                        outputs=[result_gallery, plot_status]
                    )
    
    test_btn.click(run_test_single_gui, 
                    inputs=[config_input, test_ds, test_md, ckpt_input], 
                    outputs=[test_metrics, test_plot])

if __name__ == "__main__":
    demo.launch()